// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkbsqrmrqmnrbfqrroyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYnNxcm1ycW1ucmJmcXJyb3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjMyNDIsImV4cCI6MjA2OTA5OTI0Mn0._ZQX2y6fWRAHbyxFv0ZABPA09kL6vTUwtOm9GHHuwcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});